modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/UnlikePaladin/paladins-furniture/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "pfm"
version = "${version}"
displayName = "Paladin's Furniture"
authors = "UnlikePaladin"
description = '''
A Brand-New Furniture mod for Modern Minecraft where things are functional!
'''
itemIcon = "pfm:oak_chair"
logoFile = "icon.png"
credits = "Translators: lzyzl6, MIHONO, WrenXing"

[[dependencies.pfm]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pfm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"

[modproperties.pfm]
catalogueBackground="pfm_background.png"
catalogueImageIcon=""