modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/UnlikePaladin/paladins-furniture/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "pfm"
version = "${version}"
displayName = "Paladin's Furniture"
authors = "UnlikePaladin"
description = '''
A Brand-New Furniture mod for Modern Minecraft where things are functional!
'''
logoFile = "icon.png"
credits = "Translators: lzyzl6, MIHONO, WrenXing"

[[dependencies.pfm]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pfm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"