modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/UnlikePaladin/paladins-furniture/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "pfm"
version = "${version}"
displayName = "Paladin's Furniture"
authors = "UnlikePaladin"
description = '''
A Brand-New Furniture mod for Modern Minecraft where things are functional!
'''
itemIcon = "pfm:oak_chair"
logoFile = "icon.png"
credits = "Translators: lzyzl6, MIHONO, WrenXing"

[[dependencies.pfm]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pfm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[modproperties.pfm]
catalogueBackground="pfm_background.png"
catalogueImageIcon=""

[[mixins]]
config = "pfm.mixins.json"
[[mixins]]
config = "pfm-common.mixins.json"